version: '3.6'

services:
  node-video-streaming:
    image: hyunsub/node-video-streaming:latest
    build: .
    container_name: node-video-streaming
    restart: always
    entrypoint: npm run dev
    volumes:
      - ./src:/app/src
      - ./users2.json:/app/assets/users.json
      - /archive/Movies:/archive/Movies
      - /archive/TV_Programs:/archive/TV_Programs
      - /home/hyunsub/docker/torrent/downloads/complete:/archive/torrents
    ports:
      - 8000:80
