name: Release

on:
  push:
    tags:
    - '*'

jobs:
  release:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.16.1'
    - uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
    - run: npm install
    - run: npm run eslint
    - run: npm run check
    - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - run: docker build -t embrapers263/node-video-streaming .
    - run: docker tag embrapers263/node-video-streaming:latest embrapers263/node-video-streaming:${GITHUB_REF/refs\/tags\//}
    - run: docker push embrapers263/node-video-streaming
    - run: docker push embrapers263/node-video-streaming:${GITHUB_REF/refs\/tags\//}
